### ISSUE TITLE
使用chrome-connect.js报错

### ISSUE THREAD

**Issue by huantu284** [Selection-Translator/connect.io#4]
您好，在页面引用chrome-connect.js之后，报错如图：
![image](https://user-images.githubusercontent.com/6276264/32112818-ef69cc50-bb03-11e7-9ac7-5f2088e99913.png)
我是根据文档中，
Use with <script>
部分 将js文件下载下来后，引入到html结构中的，请问怎么解决？

**Comment by huantu284** [comment]
报错信息

chrome-connect.js:82 Uncaught TypeError: Object prototype may only be an Object or null: undefined
    at Function.create (<anonymous>)
    at chrome-connect.js:82
    at chrome-connect.js:134
    at TinyEmitter (chrome-connect.js:9)
    at chrome-connect.js:10

**Comment by lmk123** [comment]
我在打包的时候忘记把 chrome-connect.js 的一个依赖 tiny-emitter 包含进去了。

你可以暂时自行引用这个依赖：

```html
<!-- 先引入 tinyemitter.js -->
<script src="https://unpkg.com/tiny-emitter/dist/tinyemitter.js"></script>
<!-- 然后引入 chrome-connect.js -->
<script src="https://unpkg.com/connect.io"></script>
```

我现在来改变一下打包配置，好了之后会在这个 issue 里回复你，这样你就不用引入 tinyemitter.js 了。

**Comment by lmk123** [comment]
已修复，下载 v3.0.1 的 chrome-connect.js 就不会有这个问题了：

https://unpkg.com/connect.io@3.0.1/dist/chrome-connect.js

**Comment by huantu284** [comment]
好的 谢谢
